spring:
  datasource:
    url: jdbc:p6spy:postgresql://${DB_URL}/${DB_NAME}?currentSchema=${DB_SCHEMA}&useUnicode=true&useJDBCCompliantTimezoneShift=true&sslmode=disable
    driverclassname: com.p6spy.engine.spy.P6SpyDriver
  flyway:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}?currentSchema=${DB_SCHEMA}&useUnicode=true&useJDBCCompliantTimezoneShift=true
