spring:
  application:
    name: Magallanes
  datasource:
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}?currentSchema=${DB_SCHEMA}&useUnicode=true&useJDBCCompliantTimezoneShift=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${DB_SCHEMA}
    out-of-order: true
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    username: ${SMTP_LOGIN}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 25000
        transport:
          protocol: smtp
    protocol: smtp
  rabbitmq:
    template:
      exchange: notification
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    addresses: ${RABBIT_URL}

server:
  port: ${PORT}

token:
  signing:
    key: ${TOKEN}

integration:
  countries:
    url: ${COUNTRIES_API_URL}

scheduled:
  trip:
    activation: 0 0 0 * * *
    completing: 0 10 0 * * *